spring.application.name=book-your-seat
spring.mongodb.uri=mongodb+srv://tomulescueduard11_db_user:zn4a6Br02BjEueyR@cluster0.kejfeww.mongodb.net/bookyourseat?appName=Cluster0
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tomulescu.eduard11@gmail.com
spring.mail.password=umet yoyv yzec oydn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
server.servlet.session.timeout=1440m
spring.datasource.url=jdbc:postgresql://db.ejssuqawaembzhlvlpbl.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=mTDwPCoRbUH2cy07
google.maps.api.key=AIzaSyBHODITMR7wOnfbALFRqa9Os2Nt3J3pWRQ
google.maps.routes.url=https://routes.googleapis.com/directions/v2:computeRoutes
openai.api.key=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
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=1
office.latitude=44.4268
office.longitude=26.1025
n8n.webhook.url=http://localhost:5678/webhook/reservation-verification
n8n.reservation-verification.webhook.url=http://localhost:5678/webhook/reservation-verification
n8n.reminder.webhook.url=http://localhost:5678/webhook/reservation-reminder
n8n.reservation-verification.recipient-email=tomulescu.eduard11@gmail.com