spring.application.name=book-your-seat
spring.mongodb.uri=mongodb+srv://<USERNAME>:<PASSWORD>@cluster0.kejfeww.mongodb.net/bookyourseat?appName=Cluster0
google.maps.api.key=AIzaSyBHODITMR7wOnfbALFRqa9Os2Nt3J3pWRQ
google.maps.routes.url=https://routes.googleapis.com/directions/v2:computeRoutes