spring.application.name=book-your-seat
spring.mongodb.uri=mongodb+srv://<USERNAME>:<PASSWORD>@cluster0.kejfeww.mongodb.net/bookyourseat?appName=Cluster0
google.maps.api.key=<GOOGLE_MAPS_API_KEY>
google.maps.routes.url=https://routes.googleapis.com/directions/v2:computeRoutes
openai.api.key=<OPENAI_API_KEY>
spring.mail.host=<MAIL_HOST>
spring.mail.port=587
spring.mail.username=<MAIL_USERNAME>
spring.mail.password=<MAIL_PASSWORD>
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true