
spring.application.name=book-your-seat
spring.mongodb.uri=mongodb+srv://antodutu_db_user:1234@cluster0.kejfeww.mongodb.net/bookyourseat?appName=Cluster0

spring.datasource.url=jdbc:postgresql://localhost:5432/bookit
spring.datasource.username=postgres
spring.datasource.password=postgre1234

spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=never

google.maps.api.key=${GOOGLE_MAPS_API_KEY:}
google.maps.routes.url=https://routes.googleapis.com/directions/v2:computeRoutes
openai.api.key=${OPENAI_API_KEY:}
office.latitude=44.451311
office.longitude=26.057355
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS_ENABLE:true}